### ISSUE TITLE
[help] Configure Releases with setOptions?

### ISSUE THREAD

**Issue by risseraka** [wprl/baucis-swagger#13]
Hi,

I'd like to enable "trust proxy" on baucis-swagger to resolve an issue I'm facing.

In Release.js:
```
function getBase (request, extra) {
  var parts = request.originalUrl.split('/');
  // Remove extra path parts.
  parts.splice(-extra, extra);
  return request.protocol + '://' + request.headers.host + parts.join('/');
};
```

Here, ```request.protocol``` is HTTP instead of HTTPS if the request pass through a reverse proxy adding ```X-Forwarded-Proto``` header field.

How is one able to configure a Release app?
My guess is using decorators' ```setOptions``` builtin but I can't find how to access the Release class.

Thanks!

**Comment by wprl** [comment]
Didn't think of it before but you could have done:

```javascript
baucis.Release.decorators(function () {
  this..enable('trust proxy');
});
```
