### ISSUE TITLE
baucis v1.0.0-candidate.10 + baucis-swagger v1.0.0-prerelease.1 + express 4.2.0 doesn't work

### ISSUE THREAD

**Issue by kbaylosis** [wprl/baucis-swagger#14]
What versions of baucis and baucis-swagger works already with express 4?

**Comment by jeffreywescott** [comment]
If anyone needs to mount somewhere other than `/api`, you might want to peek at my PR to @DavidBoike: https://github.com/DavidBoike/baucis-swagger/pull/1

**Comment by wprl** [comment]
Thanks everyone who contributed here for workarounds during the candidate phase.  I just released baucis 1.0.0 so I think the OP issue is solved now.  I'll be reviewing open PRs and issues hopefully in the near future to address and incorporate your workarounds (which may be broken now).

Again, much thanks.
